[project]
name = "embaiml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.5.3",
    "pyserial>=3.5",
    "scipy>=1.17.0",
]

[project.optional-dependencies]
rpi = [
    "mpu6050-raspberrypi",
]
